#!/bin/sh
## check_service.sh for nagios check in /Users/fresh/nagios/check_service
##
## Made by Anthony Scalisi
## <scalisi.a@gmail.com>
##
## Started on  Mon Jun 11 14:01:10 2012 Anthony Scalisi
## Last update Wed Jun 13 12:03:38 2012 Anthony Scalisi
##

OK_STATE=0
WARNING_STATE=1
CRITICAL_STATE=2
UNKNOWN_STATE=3
EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
    echo "Usage: `basename $0` [service name]"
    exit ${UNKNOWN_STATE}
fi

solaris=`uname -a | grep -qi solaris`

service="$1"

if printf "$solaris"; then
	cmd=`/usr/bin/svcs -a`
	if echo "$cmd" | grep -qEi "online.*$service"; then
		echo "OK - $service is online."
		exit ${OK_STATE}
	elif echo "$cmd" | grep -qEi "maintenance.*$service"; then
		echo "WARNING - $service is in a maitenance state."
		exit ${WARNING_STATE}
	elif echo "$cmd" | grep -qEi "degraded.*$service"; then
		echo "CRITICAL - $service is in a degraded mode."
		exit ${CRITICAL_STATE}
	elif echo "$cmd" | grep -qEi "$service"; then
		echo "CRITICAL - $service is offline."
		exit ${CRITICAL_STATE}
	else
		echo "UNKNOWN - could not determine state of $service."
		exit ${UNKNOWN_STATE}
	fi
fi