#!/bin/bash
## check_service.sh for nagios check in /Users/fresh/nagios/check_service
##
## Made by Anthony Scalisi
## <scalisi.a@gmail.com>
##
## Started on  Mon Jun 11 14:01:10 2012 Anthony Scalisi
## Last update Thu Jun 14 15:44:46 2012 Anthony Scalisi
##

OK_STATE=0
WARNING_STATE=1
CRITICAL_STATE=2
UNKNOWN_STATE=3
EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
    echo "Usage: `basename $0` [service name]"
    exit ${UNKNOWN_STATE}
fi

solaris=`uname -a | grep -qi solaris`
ubuntu=""
centos=""
suse=""

service="$1"

if printf "$solaris"; then
    svcs="/usr/bin/svcs -a"
    grep="/opt/local/bin/grep"
    if $svcs | $grep -qEi "maintenance.*$service"; then
        echo "WARNING - $service is in a maintenance state."
        exit ${WARNING_STATE}
    elif $svcs | $grep -qEi "degraded.*$service"; then
        echo "CRITICAL - $service is in a degraded mode."
        exit ${CRITICAL_STATE}
#	elif $svcs | $grep -qEi "disabled.*$service"; then
#                echo "CRITICAL - $service is disabled."
#                exit ${CRITICAL_STATE}
    elif $svcs | $grep -qEi "online.*$service"; then
        echo "OK - $service is online."
        exit ${OK_STATE}
    else
        echo "CRITICAL - $service is offline."
        exit ${CRITICAL_STATE}
    fi
else
    echo "UNKNOWN - could not determine state of $service."
    exit ${UNKNOWN_STATE}
fi